<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>${groupId}</groupId>
  <artifactId>${rootArtifactId}</artifactId>
  <version>${version}</version>
  <packaging>pom</packaging>

  <name>${rootArtifactId}</name>

  <modules>
    <module>${rootArtifactId}-api</module>
    <module>${rootArtifactId}-component</module>
  </modules>

  <properties>
    <maven.compiler.source>${javaVersion}</maven.compiler.source>
    <maven.compiler.target>${javaVersion}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.itara</groupId>
        <artifactId>itara-common</artifactId>
        <version>${itaraVersion}</version>
      </dependency>
      <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>${rootArtifactId}-api</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
