<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.itara.examples</groupId>
        <artifactId>gateway-a</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>gateway-a-impl</artifactId>
    <name>Example: gateway-a implementation</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>io.itara.examples</groupId>
            <artifactId>gateway-a-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.itara.examples</groupId>
            <artifactId>backend-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.itara</groupId>
            <artifactId>itara-common</artifactId>
        </dependency>
    </dependencies>
</project>
