use std::any::{Any, TypeId};

/// A Dispatcher maps (method_name, args, traceparent, tracestate) → result
/// on the server side.
///
/// Generated by the #[itara_component] macro for each component API trait.
/// The transport calls this when an inbound request arrives, passing the
/// W3C trace context headers it extracted from the inbound request.
///
/// traceparent and tracestate are the raw W3C header values — empty strings
/// if not present. The dispatcher restores the context from these and fires
/// observability events.
///
/// NOTE: a dedicated ItaraHeaders type and header-handling SPI are planned.
/// The raw string parameters are an interim representation.
pub type Dispatcher = Box<dyn Fn(&str, &[u8], &str, &str) -> Vec<u8> + Send + Sync>;

/// The component marker trait.
///
/// cast_to() returns the fat pointer as two words (data, vtable).
/// A *const dyn Trait is 16 bytes on all platforms — data pointer + vtable pointer.
/// Erasing to a single *const () loses the vtable. The tuple preserves both.
///
/// The pattern in every impl is fixed and mechanical — will be generated by
/// #[derive(ItaraComponent)] macro. For the PoC it is written by hand.
pub trait ItaraComponent: Any + Send + Sync {
    fn as_any(&self) -> &dyn Any;

    /// Cast self to the trait identified by trait_id.
    /// Returns (data_ptr, vtable_ptr) — both words of the fat pointer preserved.
    /// Returns None if this component does not implement the requested trait.
    fn cast_to(&self, trait_id: TypeId) -> Option<(*const (), *const ())>;
}

/// Reconstruct a &'static dyn T from the two-word fat pointer stored by cast_to().
///
/// # Safety
/// - fat must have been produced by cast_to() on a component stored in the registry.
/// - T must be the exact trait type used to produce the pointer.
/// - Only called from ItaraRegistry::get(), which guarantees process lifetime.
pub unsafe fn reconstruct_ref<T: ?Sized + 'static>(fat: (*const (), *const ())) -> &'static T {
    let fat_ptr: *const T = std::mem::transmute_copy(&fat);
    &*fat_ptr
}

/// Activator function signature exported by every component .so.
/// Receives the registry so it can pull its own dependencies.
pub type ActivatorFn = unsafe extern "C" fn(
    registry: *const crate::ItaraRegistry,
) -> Box<dyn ItaraComponent>;
