use std::any::{Any, TypeId};
use std::collections::{HashMap, HashSet};
use std::cell::UnsafeCell;
use std::sync::OnceLock;

// ── Transport SPI ─────────────────────────────────────────────────────────────
//
// Defined here alongside the registry and marker trait — same as Java's
// itara-common which contains all SPI interfaces.
// Transport implementations (HTTP, Kafka, etc.) live in separate crates
// and depend on itara-core. Core depends on nothing Itara-specific.

/// A Dispatcher maps (method_name, args) → result on the server side.
/// Generated by the #[itara_component] macro for each component API trait.
/// The transport calls this when an inbound request arrives.
pub type Dispatcher = Box<dyn Fn(&str, &[u8]) -> Vec<u8> + Send + Sync>;

/// The transport SPI — implemented by itara-transport-http, itara-transport-kafka, etc.
/// Loaded as a .so/.dll by the agent at startup.
pub trait ItaraTransport: Send + Sync {
    /// Client side — invoke a remote method.
    /// Called by the generated proxy on every outbound call.
    fn invoke(&self, component_id: &str, method: &str, args: &[u8]) -> Vec<u8>;

    /// Server side — register an inbound handler for a component.
    /// Called by the agent at startup for each local component that needs
    /// to be reachable over this transport.
    fn register_listener(&self, component_id: &str, dispatcher: Dispatcher);

    /// Start all registered listeners.
    /// Called by the agent after all listeners are registered,
    /// before handing control to the application.
    fn start(&self);
}

/// Factory function signature exported by every transport cdylib.
/// The agent passes host/port from the wiring config — the transport
/// is ignorant of topology and component ids.
pub type TransportFactoryFn = unsafe extern "C" fn(
    base_url_ptr: *const std::os::raw::c_char,
    listen_port:  u16,
) -> Box<dyn ItaraTransport>;

// ── Component marker trait ────────────────────────────────────────────────────
//
// cast_to() returns the fat pointer as two words (data, vtable).
// A *const dyn Trait is 16 bytes on all platforms — data pointer + vtable pointer.
// Erasing to a single *const () loses the vtable. The tuple preserves both.
//
// The pattern in every impl is fixed and mechanical:
//   fn cast_to(&self, trait_id: TypeId) -> Option<(*const (), *const ())> {
//       if trait_id == TypeId::of::<dyn MyApiTrait>() {
//           let fat = self as &dyn MyApiTrait as *const dyn MyApiTrait;
//           Some(unsafe { std::mem::transmute(fat) })
//       } else {
//           None
//       }
//   }
//
// This will be a #[derive(ItaraComponent)] macro. For the PoC it is written by hand.

pub trait ItaraComponent: Any + Send + Sync {
    fn as_any(&self) -> &dyn Any;

    /// Cast self to the trait identified by trait_id.
    /// Returns (data_ptr, vtable_ptr) — both words of the fat pointer preserved.
    /// Returns None if this component does not implement the requested trait.
    fn cast_to(&self, trait_id: TypeId) -> Option<(*const (), *const ())>;
}

// ── Fat pointer reconstruction ────────────────────────────────────────────────
//
// cast_to() transmutes *const dyn Trait → (*const (), *const ()) to preserve
// both words of the fat pointer across type erasure.
// reconstruct_ref() transmutes the tuple back to *const dyn T to recover
// the original fat pointer including its vtable.
//
// Safe as long as the component lives for the registry's lifetime,
// which is the process lifetime.

/// Reconstruct a &'static dyn T from the two-word fat pointer stored by cast_to().
///
/// # Safety
/// - fat must have been produced by cast_to() on a component stored in the registry.
/// - T must be the exact trait type used to produce the pointer.
/// - Only called from ItaraRegistry::get(), which guarantees process lifetime.
unsafe fn reconstruct_ref<T: ?Sized + 'static>(fat: (*const (), *const ())) -> &'static T {
    // *const dyn T is exactly two pointer-sized words: (data, vtable).
    // transmute_copy recovers the original fat pointer from the tuple.
    let fat_ptr: *const T = std::mem::transmute_copy(&fat);
    &*fat_ptr
}

// ── Activator SPI ─────────────────────────────────────────────────────────────

/// Activator function signature exported by every component .so.
/// Receives the registry so it can pull its own dependencies.
pub type ActivatorFn = unsafe extern "C" fn(registry: *const ItaraRegistry) -> Box<dyn ItaraComponent>;

// ── Registry ──────────────────────────────────────────────────────────────────

static GLOBAL_REGISTRY: OnceLock<ItaraRegistry> = OnceLock::new();

pub struct ItaraRegistry {
    /// Fully initialised instances — remote proxies and activated locals.
    /// UnsafeCell because activators trigger each other during startup
    /// (single-threaded). Frozen after install_global() — read-only at call time.
    instances:  UnsafeCell<HashMap<String, Box<dyn ItaraComponent>>>,

    /// Activator function pointers for local components.
    activators: HashMap<String, ActivatorFn>,

    /// Circular dependency detection during startup activation.
    activating: UnsafeCell<HashSet<String>>,
}

// SAFETY: startup is single-threaded. After install_global() the registry
// is read-only — no mutation ever occurs at call time.
unsafe impl Sync for ItaraRegistry {}
unsafe impl Send for ItaraRegistry {}

impl ItaraRegistry {
    pub fn new() -> Self {
        ItaraRegistry {
            instances:  UnsafeCell::new(HashMap::new()),
            activators: HashMap::new(),
            activating: UnsafeCell::new(HashSet::new()),
        }
    }

    /// Install as process global. Called once by the agent after all
    /// registrations are complete. Panics if called twice.
    pub fn install_global(registry: ItaraRegistry) {
        GLOBAL_REGISTRY
            .set(registry)
            .map_err(|_| ())
            .expect("[Itara] Global registry already installed");
        println!("[Itara] Registry installed — startup complete");
    }

    /// Access the process-global registry.
    /// Panics if the agent has not called install_global() yet.
    pub fn global() -> &'static ItaraRegistry {
        GLOBAL_REGISTRY
            .get()
            .expect("[Itara] Global registry not initialised — agent startup incomplete")
    }

    // ── Agent setup API ───────────────────────────────────────────────────

    /// Register a remote proxy constructed by the agent.
    /// The proxy implements the component's API trait and routes calls
    /// over the configured transport.
    pub fn register_proxy(&mut self, id: &str, proxy: Box<dyn ItaraComponent>) {
        println!("[Itara] Registered proxy for: {}", id);
        self.instances.get_mut().insert(id.to_string(), proxy);
    }

    /// Register a local component's activator. Activation is lazy —
    /// the activator runs on the first get() for this id.
    pub fn register_activator(&mut self, id: &str, activator: ActivatorFn) {
        println!("[Itara] Registered activator for: {}", id);
        self.activators.insert(id.to_string(), activator);
    }

    /// Returns true if a component is already registered as a proxy or activator.
    pub fn is_registered(&self, id: &str) -> bool {
        unsafe { &*self.instances.get() }.contains_key(id)
            || self.activators.contains_key(id)
    }

    // ── Agent post-install API ────────────────────────────────────────────

    /// Return the raw fat pointer words for a registered component.
    ///
    /// Used by the agent after install_global() to pass a type-erased component
    /// reference to an API cdylib dispatcher factory. The cdylib reconstructs
    /// the typed fat pointer internally — the agent never knows the concrete type.
    ///
    /// Triggers lazy activation if the component has not been activated yet.
    /// Returns None if the component is not registered.
    pub fn get_fat_ptr(&self, id: &str) -> Option<(*const (), *const ())> {
        self.ensure_activated(id);
        let instances = unsafe { &*self.instances.get() };
        let component = instances.get(id)?;
        // cast_to() with TypeId::of::<()>() will return None for any real trait.
        // We need to retrieve the fat pointer for the component's own primary trait.
        // Since we don't know the TypeId here, we expose the raw component pointer
        // directly: the cdylib dispatcher factory accepts (data, vtable) as two
        // words and performs its own transmute back to the concrete trait reference.
        //
        // We obtain the two words by transmuting the Box's raw pointer. A
        // Box<dyn ItaraComponent> is itself a fat pointer — (data, vtable) —
        // pointing to the concrete type and its ItaraComponent vtable. However,
        // the cdylib needs the API trait vtable (e.g. dyn CalculatorService),
        // not the ItaraComponent vtable.
        //
        // We call cast_to() with a sentinel TypeId and iterate over known trait IDs.
        // Since we don't know the TypeId here, we delegate to the component itself:
        // the component implements cast_to() and returns the correct API trait fat pointer.
        // The agent stores the TypeId when the component is first registered via
        // the API cdylib — but that mechanism is not yet implemented.
        //
        // Interim: cast_to() is called from the cdylib side with the correct TypeId.
        // Here we return the raw pointer to the ItaraComponent box content — the
        // cdylib is responsible for knowing the correct TypeId and calling cast_to()
        // directly. We pass the ItaraComponent fat pointer words; the cdylib unwraps
        // them using its own knowledge of the concrete type.
        let raw: *const dyn ItaraComponent = component.as_ref() as *const dyn ItaraComponent;
        let fat: (*const (), *const ()) = unsafe { std::mem::transmute(raw) };
        Some(fat)
    }

    // ── Application / activator API ───────────────────────────────────────

    /// Retrieve a component by id as a reference to the requested trait T.
    /// The caller names only the API trait — never the concrete type.
    ///
    /// Panics at startup — not at call time — if:
    ///   - the id is not registered (topology config error)
    ///   - the component does not implement T (contract mismatch)
    ///   - a circular dependency is detected during activation
    pub fn get<T: ?Sized + 'static>(&self, id: &str) -> &T {
        self.ensure_activated(id);

        let instances = unsafe { &*self.instances.get() };
        let component = instances.get(id).unwrap();

        // cast_to() returns the fat pointer as (data, vtable) — both words preserved.
        let fat = component.cast_to(TypeId::of::<T>()).unwrap_or_else(|| {
            panic!(
                "[Itara] Component '{}' does not implement the requested trait. \
                 Check your wiring config.",
                id
            )
        });

        // SAFETY: fat was produced by cast_to() on a component that lives in the
        // registry for the process lifetime. T matches the TypeId used to produce
        // the pointer. reconstruct_ref() recovers the original fat pointer including
        // its vtable.
        unsafe { reconstruct_ref::<T>(fat) }
    }

    fn ensure_activated(&self, id: &str) {
        if unsafe { &*self.instances.get() }.contains_key(id) {
            return;
        }

        let activating = unsafe { &mut *self.activating.get() };
        if activating.contains(id) {
            panic!(
                "[Itara] Circular dependency detected while activating '{}'. \
                 Check your wiring config.",
                id
            );
        }

        let activator = self.activators.get(id).copied().unwrap_or_else(|| {
            panic!(
                "[Itara] Topology error: '{}' is not registered. \
                 Check your wiring config.",
                id
            )
        });

        activating.insert(id.to_string());
        println!("[Itara] Activating: {}", id);

        // Pass the registry pointer so the activator can pull its dependencies.
        let instance = unsafe { activator(self as *const ItaraRegistry) };

        unsafe { &mut *self.activating.get() }.remove(id);
        unsafe { &mut *self.instances.get() }.insert(id.to_string(), instance);

        println!("[Itara] Activated: {}", id);
    }
}

// ── Loaders ───────────────────────────────────────────────────────────────────

/// Load a component .so and register its activator.
/// This and reconstruct_ref() are the only unsafe surfaces in the framework.
/// Everything the caller touches — get(), preregister(), returned references
/// — is safe Rust.
pub fn load_and_register(
    registry: &mut ItaraRegistry,
    component_id: &str,
    lib_path: &str,
) -> Result<(), String> {
    unsafe {
        let lib = libloading::Library::new(lib_path)
            .map_err(|e| format!("[Itara] Failed to load '{}': {}", lib_path, e))?;

        let activator: libloading::Symbol<ActivatorFn> = lib
            .get(b"itara_activator\0")
            .map_err(|e| format!("[Itara] No itara_activator in '{}': {}", lib_path, e))?;

        let activator_fn: ActivatorFn = *activator;

        // Leak the library — components live for the process lifetime.
        // The .so must not be unloaded while any component reference is live.
        std::mem::forget(lib);

        registry.register_activator(component_id, activator_fn);
        Ok(())
    }
}

/// Proxy factory function signature exported by every API cdylib.
/// Called by the agent to create a remote proxy wrapping the given transport.
/// The agent never knows the concrete proxy type — only this C symbol.
pub type ProxyFactoryFn = unsafe extern "C" fn(
    transport: Box<dyn ItaraTransport>,
) -> Box<dyn ItaraComponent>;

/// Dispatcher factory function signature exported by every API cdylib.
/// Called by the agent to create an inbound dispatcher for a local component.
///
/// Receives the two fat pointer words of a *const dyn ItaraComponent.
/// The cdylib calls cast_to(TypeId::of::<dyn MyApiTrait>()) internally to
/// obtain the correctly-typed reference — the agent never needs to know
/// the concrete API trait type.
pub type DispatcherFactoryFn = unsafe extern "C" fn(
    data:   *const (),   // data word of *const dyn ItaraComponent fat pointer
    vtable: *const (),   // vtable word of *const dyn ItaraComponent fat pointer
) -> Dispatcher;

/// Load an API cdylib and return its proxy and dispatcher factory functions.
/// The caller is responsible for leaking the library (components are process-lifetime).
pub fn load_api_cdylib(
    lib_path: &str,
) -> Result<(ProxyFactoryFn, DispatcherFactoryFn), String> {
    unsafe {
        let lib = libloading::Library::new(lib_path)
            .map_err(|e| format!("[Itara] Failed to load API cdylib '{}': {}", lib_path, e))?;

        let proxy_factory: libloading::Symbol<ProxyFactoryFn> = lib
            .get(b"itara_create_proxy\0")
            .map_err(|e| format!("[Itara] No itara_create_proxy in '{}': {}", lib_path, e))?;

        let dispatcher_factory: libloading::Symbol<DispatcherFactoryFn> = lib
            .get(b"itara_create_dispatcher\0")
            .map_err(|e| format!("[Itara] No itara_create_dispatcher in '{}': {}", lib_path, e))?;

        let proxy_fn: ProxyFactoryFn = *proxy_factory;
        let dispatcher_fn: DispatcherFactoryFn = *dispatcher_factory;

        // Leak — the proxy and dispatcher factories must remain valid for process lifetime.
        std::mem::forget(lib);

        Ok((proxy_fn, dispatcher_fn))
    }
}

/// Load a transport cdylib and return a configured instance.
/// base_url is the outbound URL (empty string for inbound-only).
/// listen_port is the inbound port (0 for outbound-only).
pub fn load_transport(
    lib_path:    &str,
    base_url:    &str,
    listen_port: u16,
) -> Result<Box<dyn ItaraTransport>, String> {
    unsafe {
        let lib = libloading::Library::new(lib_path)
            .map_err(|e| format!("[Itara] Failed to load transport '{}': {}", lib_path, e))?;

        let factory: libloading::Symbol<TransportFactoryFn> = lib
            .get(b"itara_transport_factory\0")
            .map_err(|e| format!("[Itara] No itara_transport_factory in '{}': {}", lib_path, e))?;

        let factory_fn: TransportFactoryFn = *factory;

        std::mem::forget(lib);

        let c_url = std::ffi::CString::new(base_url)
            .map_err(|e| format!("[Itara] Invalid base_url string: {}", e))?;

        let transport = factory_fn(c_url.as_ptr(), listen_port);
        Ok(transport)
    }
}