use std::any::{Any, TypeId};
use itara_core::{ItaraComponent, ItaraTransport, Dispatcher};
use itara_serializer_json as json;

// ── Contract ──────────────────────────────────────────────────────────────────

pub trait CalculatorService: ItaraComponent {
    fn add(&self, a: i64, b: i64) -> i64;
    fn multiply(&self, a: i64, b: i64) -> i64;
}

// ── Generated proxy (future: #[itara_component] macro output) ─────────────────
//
// The proxy receives a serializer_id string from the agent at construction time.
// Each method dispatches on this string to select the correct serialization path.
// No intermediate format is used — each path serializes the typed values directly.
//
// Adding a new serializer: add a match arm here and in the dispatcher below.
// The serializer id is the plain string declared in the wiring config.

pub struct CalculatorServiceProxy {
    transport:     Box<dyn ItaraTransport>,
    component_id:  String,
    serializer_id: String,
}

impl CalculatorServiceProxy {
    pub fn new(
        transport:     Box<dyn ItaraTransport>,
        component_id:  &str,
        serializer_id: &str,
    ) -> Self {
        CalculatorServiceProxy {
            transport,
            component_id:  component_id.to_string(),
            serializer_id: serializer_id.to_string(),
        }
    }
}

impl CalculatorService for CalculatorServiceProxy {
    fn add(&self, a: i64, b: i64) -> i64 {
        let payload = serialize_args_add(&self.serializer_id, a, b);
        let response = self.transport.invoke(&self.component_id, "add", &payload);
        deserialize_return_i64(&self.serializer_id, &response)
    }
 
    fn multiply(&self, a: i64, b: i64) -> i64 {
        let payload = serialize_args_multiply(&self.serializer_id, a, b);
        let response = self.transport.invoke(&self.component_id, "multiply", &payload);
        deserialize_return_i64(&self.serializer_id, &response)
    }
}

impl ItaraComponent for CalculatorServiceProxy {
    fn as_any(&self) -> &dyn Any { self }
    fn cast_to(&self, trait_id: TypeId) -> Option<(*const (), *const ())> {
        if trait_id == TypeId::of::<dyn CalculatorService>() {
            let fat = self as &dyn CalculatorService as *const dyn CalculatorService;
            Some(unsafe { std::mem::transmute(fat) })
        } else {
            None
        }
    }
}
 
// ── API cdylib symbols ────────────────────────────────────────────────────────
//
// Future: generated by #[itara_component] macro.
 
/// Create a proxy that wraps the given transport and implements CalculatorService.
/// Called by the agent when wiring an outbound connection to a remote calculator.
///
/// # Safety
/// - transport must be a valid Box<dyn ItaraTransport> produced by the agent.
/// - serializer_id must be a valid null-terminated UTF-8 string, valid for
///   the process lifetime (the agent holds it as a leaked CString).
#[unsafe(no_mangle)]
pub extern "C" fn itara_create_proxy(
    transport:     Box<dyn ItaraTransport>,
    serializer_id: *const std::os::raw::c_char,
) -> Box<dyn ItaraComponent> {
    let id = unsafe { std::ffi::CStr::from_ptr(serializer_id) }
        .to_str()
        .expect("[CalculatorApi] itara_create_proxy: serializer_id is not valid UTF-8");
    Box::new(CalculatorServiceProxy::new(transport, "calculator", id))
}
 
/// Create a dispatcher that routes inbound calls to the given component.
/// Called by the agent when wiring an inbound connection for a local component.
///
/// # Safety
/// - (data, vtable) must be the fat pointer words of a &'static dyn ItaraComponent
///   that implements CalculatorService, stored in the global registry.
/// - serializer_id must be a valid null-terminated UTF-8 string, valid for
///   the process lifetime.
#[unsafe(no_mangle)]
pub extern "C" fn itara_create_dispatcher(
    data:          *const (),
    vtable:        *const (),
    serializer_id: *const std::os::raw::c_char,
) -> Dispatcher {
    let fat: (*const (), *const ()) = (data, vtable);
    let fat_ptr: *const dyn ItaraComponent = unsafe { std::mem::transmute_copy(&fat) };
    let component: &'static dyn ItaraComponent = unsafe { &*fat_ptr };
 
    let api_fat = component
        .cast_to(TypeId::of::<dyn CalculatorService>())
        .unwrap_or_else(|| panic!(
            "[CalculatorApi] Component does not implement CalculatorService. \
             Check your wiring config."
        ));
 
    let api_fat_ptr: *const dyn CalculatorService =
        unsafe { std::mem::transmute_copy(&api_fat) };
    let service: &'static dyn CalculatorService = unsafe { &*api_fat_ptr };
 
    let id = unsafe { std::ffi::CStr::from_ptr(serializer_id) }
        .to_str()
        .expect("[CalculatorApi] itara_create_dispatcher: serializer_id is not valid UTF-8")
        .to_string();
 
    calculator_dispatcher(service, id)
}

// ── Generated dispatcher (future: #[itara_component] macro output) ────────────

pub fn calculator_dispatcher(
    component:     &'static dyn CalculatorService,
    serializer_id: String,
) -> Dispatcher {
    Box::new(move |method: &str, args: &[u8]| -> Vec<u8> {
        match method {
            "add" => {
                let (a, b) = deserialize_args_add(&serializer_id, args);
                let result = component.add(a, b);
                serialize_return_i64(&serializer_id, result)
            }
            "multiply" => {
                let (a, b) = deserialize_args_multiply(&serializer_id, args);
                let result = component.multiply(a, b);
                serialize_return_i64(&serializer_id, result)
            }
            unknown => panic!("[CalculatorDispatcher] unknown method: '{}'", unknown),
        }
    })
}
 
// ── Serialization dispatch ────────────────────────────────────────────────────
//
// One function per method per direction. Each function matches on the
// serializer id and dispatches to the correct format implementation.
// No intermediate format — each arm works directly with the typed values.
//
// Future: generated by the macro for the serializers declared in [serializers]
// of the .itara metadata file.
 
fn serialize_args_add(serializer_id: &str, a: i64, b: i64) -> Vec<u8> {
    match serializer_id {
        "json" => json::serialize(&[a, b]),
        unknown => panic!("[CalculatorProxy] add: unsupported serializer '{}'", unknown),
    }
}
 
fn serialize_args_multiply(serializer_id: &str, a: i64, b: i64) -> Vec<u8> {
    match serializer_id {
        "json" => json::serialize(&[a, b]),
        unknown => panic!("[CalculatorProxy] multiply: unsupported serializer '{}'", unknown),
    }
}
 
fn deserialize_return_i64(serializer_id: &str, bytes: &[u8]) -> i64 {
    match serializer_id {
        "json" => json::deserialize::<i64>(bytes),
        unknown => panic!("[CalculatorProxy] deserialize_return: unsupported serializer '{}'", unknown),
    }
}
 
fn deserialize_args_add(serializer_id: &str, bytes: &[u8]) -> (i64, i64) {
    match serializer_id {
        "json" => { let vals: [i64; 2] = json::deserialize(bytes); (vals[0], vals[1]) }
        unknown => panic!("[CalculatorDispatcher] add: unsupported serializer '{}'", unknown),
    }
}
 
fn deserialize_args_multiply(serializer_id: &str, bytes: &[u8]) -> (i64, i64) {
    match serializer_id {
        "json" => { let vals: [i64; 2] = json::deserialize(bytes); (vals[0], vals[1]) }
        unknown => panic!("[CalculatorDispatcher] multiply: unsupported serializer '{}'", unknown),
    }
}
 
fn serialize_return_i64(serializer_id: &str, value: i64) -> Vec<u8> {
    match serializer_id {
        "json" => json::serialize(&value),
        unknown => panic!("[CalculatorDispatcher] serialize_return: unsupported serializer '{}'", unknown),
    }
}
