use std::any::{Any, TypeId};
use itara_core::{ItaraComponent, ItaraTransport, Dispatcher};

// ── Contract ──────────────────────────────────────────────────────────────────

pub trait CalculatorService: ItaraComponent {
    fn add(&self, a: i64, b: i64) -> i64;
    fn multiply(&self, a: i64, b: i64) -> i64;
}

// ── Generated proxy (future: #[itara_component] macro output) ─────────────────

pub struct CalculatorServiceProxy {
    transport:    Box<dyn ItaraTransport>,
    component_id: String,
}

impl CalculatorServiceProxy {
    pub fn new(transport: Box<dyn ItaraTransport>, component_id: &str) -> Self {
        CalculatorServiceProxy { transport, component_id: component_id.to_string() }
    }
}

impl CalculatorService for CalculatorServiceProxy {
    fn add(&self, a: i64, b: i64) -> i64 {
        let payload = serde_json::to_vec(&[a, b]).expect("[CalculatorProxy] Failed to serialize args");
        let response = self.transport.invoke(&self.component_id, "add", &payload);
        serde_json::from_slice::<i64>(&response).expect("[CalculatorProxy] Expected i64 from add")
    }
    fn multiply(&self, a: i64, b: i64) -> i64 {
        
        let payload = serde_json::to_vec(&[a, b]).expect("[CalculatorProxy] Failed to serialize args");
        let response = self.transport.invoke(&self.component_id, "multiply", &payload);
        serde_json::from_slice::<i64>(&response).expect("[CalculatorProxy] Expected i64 from multiply")
    }
}

impl ItaraComponent for CalculatorServiceProxy {
    fn as_any(&self) -> &dyn Any { self }
    fn cast_to(&self, trait_id: TypeId) -> Option<(*const (), *const ())> {
        if trait_id == TypeId::of::<dyn CalculatorService>() {
            let fat = self as &dyn CalculatorService as *const dyn CalculatorService;
            Some(unsafe { std::mem::transmute(fat) })
        } else {
            None
        }
    }
}
 
// ── API cdylib symbols ────────────────────────────────────────────────────────
//
// These are the two C-compatible symbols exported by every API cdylib.
// The agent loads the cdylib at runtime and calls these symbols — it never
// knows about CalculatorService as a Rust type.
//
// Future: generated by #[itara_component] macro. For now, written by hand.
// The pattern is identical for every API crate — only the proxy type and
// component id string change.
 
/// Create a proxy that wraps the given transport and implements CalculatorService.
/// Called by the agent when wiring an outbound connection to a remote calculator.
///
/// # Safety
/// transport must be a valid Box<dyn ItaraTransport> produced by the agent.
#[unsafe(no_mangle)]
pub extern "C" fn itara_create_proxy(
    transport: Box<dyn ItaraTransport>,
) -> Box<dyn ItaraComponent> {
    Box::new(CalculatorServiceProxy::new(transport, "calculator"))
}
 
/// Create a dispatcher that routes inbound calls to the given component.
/// Called by the agent when wiring an inbound connection for a local calculator.
///
/// Receives the two fat pointer words of a *const dyn ItaraComponent.
/// Calls cast_to(TypeId::of::<dyn CalculatorService>()) internally to obtain
/// the correctly-typed reference — the agent never needs to know this type.
///
/// # Safety
/// (data, vtable) must be the fat pointer words of a &'static dyn ItaraComponent
/// that implements CalculatorService, stored in the global registry.
#[unsafe(no_mangle)]
pub extern "C" fn itara_create_dispatcher(
    data:   *const (),
    vtable: *const (),
) -> Dispatcher {
    // Reconstruct the &'static dyn ItaraComponent fat pointer from its two words.
    let fat: (*const (), *const ()) = (data, vtable);
    let fat_ptr: *const dyn ItaraComponent = unsafe { std::mem::transmute_copy(&fat) };
    let component: &'static dyn ItaraComponent = unsafe { &*fat_ptr };
 
    // Ask the component to cast itself to dyn CalculatorService.
    // cast_to() returns the API trait fat pointer — correctly typed for this cdylib.
    let api_fat = component
        .cast_to(TypeId::of::<dyn CalculatorService>())
        .unwrap_or_else(|| panic!(
            "[CalculatorApi] Component does not implement CalculatorService. \
             Check your wiring config."
        ));
 
    // Reconstruct the &'static dyn CalculatorService reference.
    let api_fat_ptr: *const dyn CalculatorService =
        unsafe { std::mem::transmute_copy(&api_fat) };
    let service: &'static dyn CalculatorService = unsafe { &*api_fat_ptr };
 
    calculator_dispatcher(service)
}

// ── Generated dispatcher (future: #[itara_component] macro output) ────────────

pub fn calculator_dispatcher(component: &'static dyn CalculatorService) -> Dispatcher {
    Box::new(move |method: &str, args: &[u8]| -> Vec<u8> {
        match method {
            "add" => {
                let vals: [i64; 2] = serde_json::from_slice(args)
                    .expect("[CalculatorDispatcher] add: expected [i64, i64]");
                serde_json::to_vec(&component.add(vals[0], vals[1]))
                    .expect("[CalculatorDispatcher] Failed to serialize result")
            }
            "multiply" => {
                let vals: [i64; 2] = serde_json::from_slice(args)
                    .expect("[CalculatorDispatcher] multiply: expected [i64, i64]");
                serde_json::to_vec(&component.multiply(vals[0], vals[1]))
                    .expect("[CalculatorDispatcher] Failed to serialize result")
            }
            unknown => panic!("[CalculatorDispatcher] unknown method: '{}'", unknown),
        }
    })
}