[workspace]
members = [
    "itara-core",
    "itara-config",
    "itara-libdir",
    "itara-agent",
    "calculator-api",
    "calculator-component",
    "gateway-api",
    "gateway-component",
    "itara-transport-http",
    "itara-serializer-json",
    "itara-observability-logging",
    "itara-observability-otel",
    "itara-context-handler",
    "itara-cli",
]
resolver = "2"
