package topos.agent.config;

import java.util.List;

/**
 * The per-JVM wiring config slice.
 *
 * Generated by the orchestrator and passed to the agent as a YAML file.
 * The file path is provided via the -D JVM argument: -Dtopos.config=/path/to/slice.yaml
 *
 * This class is the Java representation of that file.
 * Shared between the orchestrator and the agent via topos-common.
 *
 * Example YAML:
 *
 *   components:
 *     - id: "order-service"
 *       activator: "com.example.order.OrderActivator"
 *     - id: "pricing-service"
 *       activator: "com.example.pricing.PricingActivator"
 *
 *   connections:
 *     - from: "order-service"
 *       to: "pricing-service"
 *       type: direct
 *
 *     - from: ""
 *       to: "order-service"
 *       type: http
 *       host: "localhost"
 *       port: 8080
 */
public class WiringConfig {

    private List<ComponentEntry> components;
    private List<ConnectionEntry> connections;

    public List<ComponentEntry> getComponents() { return components; }
    public void setComponents(List<ComponentEntry> components) { this.components = components; }

    public List<ConnectionEntry> getConnections() { return connections; }
    public void setConnections(List<ConnectionEntry> connections) { this.connections = connections; }

    // ── Inner types ────────────────────────────────────────────────────────

    public static class ComponentEntry {
        /** The component id — must match @ComponentInterface(id) */
        private String id;
        /** Fully qualified activator class name. Null for remote-only components. */
        private String activator;

        public String getId() { return id; }
        public void setId(String id) { this.id = id; }
        public String getActivator() { return activator; }
        public void setActivator(String activator) { this.activator = activator; }
    }

    public static class ConnectionEntry {
        /**
         * Caller component id. Empty or null means the caller is external
         * (outside the Topos topology) — this connection defines an inbound
         * entry point for the 'to' component.
         */
        private String from;
        /** Callee component id. */
        private String to;
        /** Connection type: direct | http */
        private String type;
        /** For http connections: the host of the remote JVM. */
        private String host;
        /** For http connections: the port of the remote JVM. */
        private int port;

        public String getFrom() { return from; }
        public void setFrom(String from) { this.from = from; }
        public String getTo() { return to; }
        public void setTo(String to) { this.to = to; }
        public String getType() { return type; }
        public void setType(String type) { this.type = type; }
        public String getHost() { return host; }
        public void setHost(String host) { this.host = host; }
        public int getPort() { return port; }
        public void setPort(int port) { this.port = port; }

        public boolean isExternal() {
            return from == null || from.isBlank();
        }

        public boolean isDirect() {
            return "direct".equalsIgnoreCase(type);
        }

        public boolean isHttp() {
            return "http".equalsIgnoreCase(type);
        }
    }
}
