package io.itara.serializer.protobuf;

import io.itara.serializer.protobuf.fixtures.CalculatorRequest;
import io.itara.serializer.protobuf.fixtures.CalculatorResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Round-trips CalculatorRequest / CalculatorResponse — real classes
 * generated by protoc from calculator_fixture.proto (src/test/proto),
 * compiled by the build via protobuf-maven-plugin — through
 * ProtoItaraSerializer, with zero code in this test or in
 * ProtoItaraSerializer that knows either type by name.
 *
 * This is the piece {@link ProtoItaraSerializerTest} could not prove on
 * its own: that class's StringValue/Int32Value stand-ins are bundled,
 * already-compiled types shipped inside the protobuf-java jar, not
 * something protoc generated for us from a .proto file we wrote. This
 * class exists specifically to close that gap — the sub-issue's
 * acceptance criterion is "works against a hand-written .proto-generated
 * API artifact without any artifact-specific serializer code," and this
 * is that hand-written .proto, compiled and exercised for real.
 */
@DisplayName("ProtoItaraSerializer against a hand-written protoc-generated fixture")
class ProtoItaraSerializerFixtureTest {

    private static final ProtoSerializerConfig TEST_CONFIG = ProtoSerializerConfig.INSTANCE;

    private ProtoItaraSerializer serializer;

    @BeforeEach
    void setUp() {
        serializer = new ProtoItaraSerializer();
    }

    @Test
    @DisplayName("round-trips the request as a method argument")
    void roundtripsRequestArgument() throws Exception {
        CalculatorRequest request = CalculatorRequest.newBuilder()
                .setA(3)
                .setB(4)
                .build();

        byte[] bytes = serializer.serializeArgs(new Object[]{ request }, TEST_CONFIG);
        Object[] result = serializer.deserializeArgs(bytes, new Class<?>[]{ CalculatorRequest.class }, TEST_CONFIG);

        assertEquals(1, result.length);
        assertEquals(request, result[0]);

        CalculatorRequest decoded = (CalculatorRequest) result[0];
        assertEquals(3, decoded.getA());
        assertEquals(4, decoded.getB());
    }

    @Test
    @DisplayName("round-trips the response as a return value")
    void roundtripsResponseResult() throws Exception {
        CalculatorResponse response = CalculatorResponse.newBuilder()
                .setResult(7)
                .build();

        byte[] bytes = serializer.serializeResult(response, TEST_CONFIG);
        Object result = serializer.deserializeResult(bytes, CalculatorResponse.class, TEST_CONFIG);

        assertEquals(response, result);
        assertEquals(7, ((CalculatorResponse) result).getResult());
    }

    @Test
    @DisplayName("a full call shape: request in, response out, exactly as a real proto-format method would")
    void fullCallShape() throws Exception {
        CalculatorRequest request = CalculatorRequest.newBuilder().setA(10).setB(32).build();

        byte[] requestBytes = serializer.serializeArgs(new Object[]{ request }, TEST_CONFIG);
        Object[] deserializedArgs = serializer.deserializeArgs(
                requestBytes, new Class<?>[]{ CalculatorRequest.class }, TEST_CONFIG);
        CalculatorRequest received = (CalculatorRequest) deserializedArgs[0];

        // Stand-in for the actual business logic a real component would run.
        CalculatorResponse response = CalculatorResponse.newBuilder()
                .setResult(received.getA() + received.getB())
                .build();

        byte[] responseBytes = serializer.serializeResult(response, TEST_CONFIG);
        Object finalResult = serializer.deserializeResult(responseBytes, CalculatorResponse.class, TEST_CONFIG);

        assertEquals(42, ((CalculatorResponse) finalResult).getResult());
    }
}
